# Generated by Django 3.0.4 on 2020-03-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('community_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='communities.Community')),
                ('group_description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('communities.community',),
        ),
    ]
