# Generated by Django 3.0.4 on 2020-06-03 16:39

import concord.actions.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='governor_condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
        migrations.AddField(
            model_name='group',
            name='owner_condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
    ]
