# Generated by Django 3.0.4 on 2020-06-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200603_1639'),
    ]

    operations = [
    ]


"""
In Concord, we needed to manually add the default Template field. Maybe we don't here because we didn't do
the intervening migration where the field was null?  If we do, use the code below.




def postgres_migration_prep(apps, schema_editor):

    # Find all community models that have a changing condition field, aka all
    # communities that inherit from the abstract BaseCommunity model

    model_list = []
    for model in settings.ALTERNATIVE_COMMUNITY_MODELS:
        model_class = apps.get_model(model["app_name"], model["model_name"])
        model_list.append(model_class)

    # For all community objects in the DB, give them a default template field
    # need to get all that have is_community attr

    from concord.actions.customfields import Template

    for model in model_list:

        update_parameters = {
            "owner_condition": Template(system=True),
            "governor_condition": Template(system=True)
        }
        model.objects.update(**update_parameters)



class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200603_1639'),
    ]

    operations = [
        migrations.RunPython(postgres_migration_prep, migrations.RunPython.noop)
    ]

"""