# Generated by Django 3.0.4 on 2020-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200603_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='special',
            field=models.CharField(choices=[('None', 'None'), ('Gov', 'Governance Forum')], default='None', max_length=4),
        ),
    ]
