# Generated by Django 3.0.7 on 2020-10-13 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditionals', '0007_auto_20201009_1809'),
        ('groups', '0005_auto_20200920_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='governor_condition',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner_condition',
        ),
    ]