# Generated by Django 3.0.7 on 2021-04-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_merge_20210223_1935'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_emails', models.CharField(choices=[('now', 'Immediately'), ('day', 'Daily'), ('nev', 'Never')], default='now', max_length=3)),
                ('always_notify_everything', models.BooleanField(default=False)),
                ('always_notify_approval', models.BooleanField(default=True)),
                ('always_notify_creator', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notify_settings', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('email_type', models.CharField(choices=[('now', 'Immediately'), ('day', 'Daily'), ('nev', 'Never')], default='nev', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
