# Generated by Django 3.0.7 on 2021-04-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationssettings',
            name='always_notify_action_resolved',
            field=models.BooleanField(default=True),
        ),
    ]
