name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: kybern_db_superuser
          POSTGRES_PASSWORD: elephant
          POSTGRES_DB: kybern_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install git+https://f23bc53183ac718cff2174b3d43ec925dc0e26bd@github.com/glizzan/glizzan-concord
        pip install -U selenium
        git clone git://github.com/cobrateam/splinter.git
        cd splinter
        python setup.py install
        cd ..
    - name: Run Tests
      run: |
        cd kybern
        python manage.py test
