name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: kybern_db_superuser
          POSTGRES_PASSWORD: elephant
          POSTGRES_DB: kybern_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck ---
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: |
        sudo apt-get install python-dev libpq-dev
    - name: install chromedriver
      run: |
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        python -m pip install git+https://f23bc53183ac718cff2174b3d43ec925dc0e26bd@github.com/glizzan/glizzan-concord
        pip install -U selenium
    - name: Run Tests
      run: |
        cd kybern
        python manage.py test
    - name: Lint code
      run: |
        cd kybern
        flake8 .
